"""create owner_report_exports

Revision ID: b3ee858ca7eb
Revises: fc01abbad52d
Create Date: 2026-03-26 22:44:54.947491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ee858ca7eb'
down_revision: Union[str, Sequence[str], None] = 'fc01abbad52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_report_exports',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_report_exports_created_at'), 'owner_report_exports', ['created_at'], unique=False)
    op.create_index(op.f('ix_owner_report_exports_owner_id'), 'owner_report_exports', ['owner_id'], unique=False)
    op.create_index(op.f('ix_owner_report_exports_report_type'), 'owner_report_exports', ['report_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owner_report_exports_report_type'), table_name='owner_report_exports')
    op.drop_index(op.f('ix_owner_report_exports_owner_id'), table_name='owner_report_exports')
    op.drop_index(op.f('ix_owner_report_exports_created_at'), table_name='owner_report_exports')
    op.drop_table('owner_report_exports')
    # ### end Alembic commands ###
