"""codigo postal

Revision ID: fc01abbad52d
Revises: c4d1be2a8c80
Create Date: 2026-03-23 23:25:05.282346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc01abbad52d'
down_revision: Union[str, Sequence[str], None] = 'c4d1be2a8c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_properties_postal_code'), 'properties', ['postal_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_postal_code'), table_name='properties')
    op.drop_column('properties', 'postal_code')
    # ### end Alembic commands ###
